# Generated by Django 4.0.2 on 2022-03-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='../images/'),
        ),
    ]
