# Generated by Django 4.0.2 on 2022-03-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
