# Generated by Django 4.0.2 on 2022-03-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.DeleteModel(
            name='Write',
        ),
    ]
